### ISSUE TITLE
Help with build (no style.css)

### ISSUE THREAD

**Issue by 0E800** [cjstewart88/nirc#94]
Following instructions, I receive errors about lodash being depreciated. 

When I run grunt build I get errors about needing to have ruby and sass installed in PATH.

Running grunt build --force completes with errors.

localhost:3000 loads and I am able to connect to IRC server but it looks like it is not loading the style.css.

May you please help troubleshoot?

**Comment by bblack** [comment]
> Following instructions, I receive errors about lodash being depreciated.

Assuming you mean on `npm install`, those are warnings, not errors, so they shouldn't cause any problems.

> When I run grunt build I get errors about needing to have ruby and sass installed in PATH.
> 
> Running grunt build --force completes with errors.
> 
> localhost:3000 loads and I am able to connect to IRC server but it looks like it is not loading the style.css.

Install ruby and sass.
